services:
  chess-training-app:
    build:
      context: .
      dockerfile: ./apps/chess-training-app/Dockerfile.dev
    working_dir: /app/apps/chess-training-app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - puzzles-api
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - chess-app-net

  puzzles-api:
    build:
      context: .
      dockerfile: ./apps/puzzles-api/Dockerfile.dev
    working_dir: /app/apps/puzzles-api
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '4000:4000'
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - chess-app-net

  tactics-finder:
    build:
      context: ./apps/tactics-finder
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./apps/tactics-finder:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - chess-app-net

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - chess-app-net

networks:
  chess-app-net:
    driver: bridge
