services:
  chess-training-app:
    command: yarn start
    environment:
      - NODE_ENV=production
    volumes: []

  puzzles-api:
    command: node dist/index.js
    environment:
      - NODE_ENV=production
    volumes: []

  tactics-finder:
    environment:
      - ENV=production
    volumes: []
